spring:
  application:
    name: api-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-tqa5w28sfr1gvzd1.us.auth0.com/
          audiences: https://api.fitnessai.com
  cloud:
    gateway:
      default-filters:
        - AddRequestHeader=X-User-ID,
        - RemoveRequestHeader=Cookie

      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/**
        - id: activity-service
          uri: lb://ACTIVITY-SERVICE
          predicates:
            - Path=/api/activities/**
        - id: ai-service
          uri: lb://AI-SERVICE
          predicates:
            - Path=/api/recommendations/**

server:
  port: 8080

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/