server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://ep-tight-frost-a881q2wm-pooler.eastus2.azure.neon.tech/fitnessai?sslmode=require
    username: fitnessai_owner
    password: npg_2zj8YdfZtygx
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
